### PR TITLE
Removed ORModuleManager in favor of ORProjectManager.

### PR DESCRIPTION
**Pull request by JohnPucciarelli**
- Removed ORModuleManager since it incorrectly assumed that configuration files were tied to modules (one configuration file per module). This broke monorepoos with multiple nested configuration files and only 1 top-level module.

 - Created ORProjectManager that uses `FilenameIndex::getVirtualFilesByName` to find configuration files for BS, Dune, Esy.

 - Added project configuration files to `ORIndexableFileNamesProvider`. This change should be reviewed as I'm not sure what other steps might be involved in getting configuration files properly indexed.  

I wanted to create tests for ORProjectManager but I was unsure how to populate the file indexer when extending `ORBasePlatformTestCase`. I am able to write tests for this using mockito to mock `FilenameIndex::getVirtualFilesByName` but this was previously discouraged.

@giraud any suggestions for how to test the filename index? Otherwise I will fallback to mockito.

Lastly, `ORProjectManager::isBsProject` can be used to fix the BuckleScriptToolWindow issue we encountered today that was fixed temporarily with #229 .

### CODE REVIEW

**Comment by giraud** [comment]
I am not in favor of this move.
Sources are module related, a project is just a group of modules.
Even if modules can't be manipulated in IDE other than IDEA, they are still present. I think everything is still architectured around that module entity.
For source manipulatiion, project doesn't seem to be the good abstraction.

**Comment by giraud** [comment]
For tests, I really doubt the usefulness of a test that mock the idea indexes. But I don't have a clear answer for an alternative neither, so let's go with mockito for that one.

**Comment by JohnPucciarelli** [comment]
> I am not in favor of this move.
> Sources are module related, a project is just a group of modules.
> Even if modules can't be manipulated in IDE other than IDEA, they are still present. I think everything is still architectured around that module entity.
> For source manipulatiion, project doesn't seem to be the good abstraction (just my understanding).

To clarify, this class is primarily intended to be used to determine if Bs, Dune or Esy configurations are present within a project. For example, it can be used to decide which tool windows should be visible.

It is not going to be used to find the configuration file nearest to a file being edited. For that, I can restore the ModuleManager.

The issue with using the ModuleManager for determining which configurations are present is that it requires a traversal of each module and then each module's file contents (recursively). This is expensive.

The benefit of using the ProjectManager is that it the FilenameIndex provides constant time look-ups for files by name. This is more efficient than having to traverse each module's file contents.

**Comment by giraud** [comment]
my bad then.
but you have a lot of public methods in that class that looks like what one could find in a module manager, like all the find* functions. given your explanation it seems that only the is* function should be made public ?

**Comment by JohnPucciarelli** [comment]
> my bad then.
> but you have a lot of public methods in that class that looks like what one could find in a module manager, like all the find* functions. given your explanation it seems that only the is* function should be made public ?

I debated making those private as well / removing them altogether. I thought they _could_ be useful in the future but I will remove them for now and restore them if needed. Don't want to pollute the codebase with unnecessary methods.

**Comment by giraud** [comment]
it's better to make them private, because I think that if you need to find one of these files, it should be done at the module level, not the project.

**Comment by giraud** [comment]
@JohnPucciarelli can you resolve the conflict and I'll merge ?

**Pull request merged**
